extensions:
    pim-product-model-edit-form-attribute-description:
        module: dnd/product-edit-form/attributes/description
        parent: pim-product-model-edit-form-attributes
        targetZone: self
        position: 100